### ISSUE TITLE
Accessing the Web UI in 2.7.2-rc1 fails with a timeout

### ISSUE THREAD

**Issue by tkirkland** [djGrrr/8311-was-110-firmware-builder#16]
Device: UCG Cloud Max
Previous OS: 2.7.1

I can still reach the web UI if I manually apply the SNAT rule from SSH.

I'm happy to supply whatever you need log-wise.  Just advise.

**Comment by djGrrr** [comment]
have you added the appropriate static route?

**Comment by C4Wiz** [comment]
the SNAT rule is no longer needed, but the ip addr add dev eth9 local 192.168.11.2/24 command from the terminal is

**Comment by djGrrr** [comment]
Neither is needed, you just need a static route, unless you're on an ISP such as Bell that uses PPPoE, then yes, you need to add the IP.

**Comment by C4Wiz** [comment]
> Neither is needed, you just need a static route, unless you're on an ISP such as Bell that uses PPPoE, then yes, you need to add the IP.

you responded as i was editing my post,

**Comment by C4Wiz** [comment]
perhaps add this screenshot to the github page or the wiki

**Comment by tkirkland** [comment]
I'm sorry for not replying sooner. I do not have a static route defined in the UI, nor do I have an alias IP set in the SSH shell. I was using the modded firmware alone. Verification of active firmware:
![image](https://github.com/user-attachments/assets/f2394e1d-5e43-46d8-9763-0380b1a8ec7d)
ATT V4 IP blacked out:
![image](https://github.com/user-attachments/assets/cf05641d-7e6e-4a7c-a257-63b8d4a22aa5)

If I deleted the SNAT rule that was added via iptables:
![image](https://github.com/user-attachments/assets/e44a8a52-ee64-4ba8-9679-60fb0cd7344b) etc
and remove the static IP alias on the same interface as image one, I immediately lose access to the stick's UI.
The stick's IP is the default, and nothing else is changed.

**Comment by C4Wiz** [comment]
Reboot the gateway max, then add the static route in the screenshot:

https://private-user-images.githubusercontent.com/3883521/379403117-56ba6483-e0fb-4c47-b98a-3a1ea08e80fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MzMyMDcsIm5iZiI6MTcyOTczMjkwNywicGF0aCI6Ii8zODgzNTIxLzM3OTQwMzExNy01NmJhNjQ4My1lMGZiLTRjNDctYjk4YS0zYTFlYTA4ZTgwZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMDEyMTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQ3MjAyMTgyMWI1Y2ZhODFiOWM1ODE1NjE2Zjc0MzM0NWZhYWJhZmU5ZDBmOTBhN2VhZGRhN2U0ZGFlNzBmNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.7EN64-Ae3wOjTjTD1UJ90Hjg46nQ-2kdJkHbDowDu2g

**Comment by tkirkland** [comment]
Aye, working like a charm.  Thank you, all.
