### ISSUE TITLE
Optical Status Temp conversion incorrect

### ISSUE THREAD

**Issue by C4Wiz** [djGrrr/8311-was-110-firmware-builder#17]
48 C is 118.4 F not sure what 321 K is for

![Screenshot 2024-10-23 at 1 34 12 PM](https://github.com/user-attachments/assets/31b2c50f-4c83-4599-a3e7-496bd57130a6)

**Comment by djGrrr** [comment]
K = Kelvin

**Comment by C4Wiz** [comment]
why would kelvin be relevent? as opposed to Fahrenheit?

**Comment by djGrrr** [comment]
I have no control over the output from these pages, they are strait from the `pontop` application.

**Comment by C4Wiz** [comment]
> I have no control over the output from these pages, they are strait from the `pontop` application.

oh, ok. thank you for the reply
