### ISSUE TITLE
Local Time is Incorrect

### ISSUE THREAD

**Issue by schroedingerscode** [djGrrr/8311-was-110-firmware-builder#2]
I have a ECI Networks EN-XGSFPP-OMAC-V2 with the 8311 Community Firmware [basic] - v2.4.0 (9c443bf) installed.

Everything seems to work fine, but an annoyance is that the `Local Time` as reported by the module is incorrect, and I cannot find a way to change it. I have attempted to add a NTP server in the 8311 > Configuration > Device menu, but that had no effect even after reboot. 

It seems as though the `Local Time` always defaults back to the firmware release date (4 Apr 2024) after reboot. Again, this doesn't seem to be causing any issues with the ISP, but it makes the log fidelity a little less than desirable.

**Comment by djGrrr** [comment]
What exactly did you set the NTP server to? It must be a NTP server reachable by the stick, ie. on the port the stick is plugged into. It does not support servers on the internet. Generally you would be running the NTP server on your router.

**Comment by C4Wiz** [comment]
> What exactly did you set the NTP server to? It must be a NTP server reachable by the stick, ie. on the port the stick is plugged into. It does not support servers on the internet. Generally you would be running the NTP server on your router.

i have a ntp server running on my lan, and i have the ip of the server on the stick but time is still wrong.

**Comment by djGrrr** [comment]
> > What exactly did you set the NTP server to? It must be a NTP server reachable by the stick, ie. on the port the stick is plugged into. It does not support servers on the internet. Generally you would be running the NTP server on your router.
> 
> i have a ntp server running on my lan, and i have the ip of the server on the stick but time is still wrong.

This is not a bug in the firmware but a configuration issue on your end, this is not the place to get support for that. Ask for help in the Discord server if you need help solving it.

**Comment by C4Wiz** [comment]
> > > What exactly did you set the NTP server to? It must be a NTP server reachable by the stick, ie. on the port the stick is plugged into. It does not support servers on the internet. Generally you would be running the NTP server on your router.
> > 
> > 
> > i have a ntp server running on my lan, and i have the ip of the server on the stick but time is still wrong.
> 
> This is not a bug in the firmware but a configuration issue on your end, this is not the place to get support for that. Ask for help in the Discord server if you need help solving it.

i asked in the discord but got no reply

**Comment by djGrrr** [comment]
> > > > What exactly did you set the NTP server to? It must be a NTP server reachable by the stick, ie. on the port the stick is plugged into. It does not support servers on the internet. Generally you would be running the NTP server on your router.
> > > 
> > > 
> > > i have a ntp server running on my lan, and i have the ip of the server on the stick but time is still wrong.
> > 
> > 
> > This is not a bug in the firmware but a configuration issue on your end, this is not the place to get support for that. Ask for help in the Discord server if you need help solving it.
> 
> i asked in the discord but got no reply

Then ask again
