### ISSUE TITLE
Help with compiling firmware

### ISSUE THREAD

**Issue by inijr1** [djGrrr/8311-was-110-firmware-builder#22]
I’m trying to compile the firmware using build.sh, but I can’t seem to find the stock image files (bootcore.bin, kernel.bin, and rootfs.img). 
Could you let me know where to get these files or if there's another way to compile without them?

Also is it possible to use the 8311 firmware from release to compile instead?
Is there a detailed compilation guide available?

**Comment by djGrrr** [comment]
Please visit our [Discord Server](https://discord.pon.wiki/) for help on how where to get the stock files to build with.
