### ISSUE TITLE
Time questions

### ISSUE THREAD

**Issue by C4Wiz** [djGrrr/8311-was-110-firmware-builder#26]
if the WAS-110 cannot reach the local network nor can it reach the internet, the ntp portion of the webui is pointless, i can set the correct local time using (date -s 'yyyy-mm-dd xx:xx:xx') but when i try to tell the hwclock to use it whith this command: (hwclock --hctosys) i get this: hwclock: can't open '/dev/misc/rtc': No such file or directory

does the stick not have a hwclock?

is it possible to get a ui button to sync the date and time to the machine the webui was accessed from?

**Comment by djGrrr** [comment]
The NTP setting is not in any way pointless, you just need to expose NTP on whatever interface/VLAN/subnet the stick management is on.

The stick of course does not have a hardware clock, that would require a battery.

There wouldn't really be any point in having a way to set the time via the webui, as it would simply be lost the next time the stick was rebooted.

**Comment by C4Wiz** [comment]
would you care to share how i do that if i am running a ntp server in a docker container on unraid? or do i need to ask in the discord?

**Comment by djGrrr** [comment]
Yes, discord is the right place to get support.
