### ISSUE TITLE
Local time is not correct on WAS-110

### ISSUE THREAD

**Issue by MarinSNB** [djGrrr/8311-was-110-firmware-builder#29]
Just upgraded WAS-110 to 2.8.0 firmware. The local time reported on the main/status page of the stick was not correct after the upgrade. I am on Central time (America/Chicago) but the time reported on the WAS-110 was 17:34.  The correct local time should have been 15:34. So the stick reported a local time that was 2 hours ahead of mine.

I went to Device page of the stick and changed the local time to America/Chicago (was previously set at UTC). After making this change, the local time reported on the status page of the stick remained the same at 17:36. Then I decided to reboot the stick and noticed that now for some reason the reported local time on the main status page changed to 11:38 (2 hours behind my local time).

Not sure if I am doing something wrong on my end but I thought of reporting this occurrence here instead of the Discord channel. I apologize if this is already a known issue and working on a fix. Thanks much!

**Comment by MarinSNB** [comment]
Now I am thinking that this could be due to the stick not being able communicate with the internet so it has no way to properly sync its time with that of an NTP server.

**Comment by djGrrr** [comment]
The stick does not have a hardware clock, so there is no way for it to have the correct time without setting it after booting. There is a NTP server setting but it requires the server to be accessible from the management interface. The time at bootup is set to the rootfs generation time,
