### ISSUE TITLE
Cannot set management interface gateway to 192.168.11.1

### ISSUE THREAD

**Issue by diegs** [djGrrr/8311-was-110-firmware-builder#3]
I believe because the default management IP is 192.168.11.1, and the default gateway is defined as "the management IP, i.e. no gateway, if unset", you can't actually set it to 192.168.11.1. If you enter that value and click save, it goes back to being blank.

However the default gateway on the interface is unset, not literally 192.168.11.1, so this prevents you from using 192.168.11.1 as a gateway.

Workaround was to change my router IP to 192.168.11.254 and set that as the gateway on the managment interface.

**Comment by djGrrr** [comment]
Fixed in abcc8b8
